"""
FairGrade AI — Streamlit dashboard for side-by-side model comparison.

Loads artifacts produced by ``train.py`` and builds inference features with the
same helpers as training (:func:`data_prep.build_feature_matrix` and
:func:`data_prep.align_to_training_columns`). No API keys, credentials, or
absolute filesystem paths are used.

Security: only load ``baseline_model.pkl`` and ``fair_model.pt`` generated by
your own local ``train.py`` run (pickle/torch deserialization risk).
"""

from __future__ import annotations

import json
import pickle
from pathlib import Path

import pandas as pd
import streamlit as st
import torch

from data_prep import align_to_training_columns, build_feature_matrix
from train import (
    BASELINE_MODEL_PATH,
    FAIR_MODEL_PATH,
    METRICS_PATH,
    NN_DROPOUT,
    NN_HIDDEN_SIZE,
    PassPredictor,
    predict_neural_network,
)

# Sidebar labels mapped to UCI education codes (0–4).
EDUCATION = ["None", "Primary", "5th–9th grade", "Secondary", "Higher"]
JOBS = ["at_home", "health", "other", "services", "teacher"]
REASONS = ["course", "home", "other", "reputation"]


@st.cache_resource
def load_xgb() -> tuple[object, list[str]]:
    """
    Load the pickled XGBoost baseline and training feature column names.

    The artifact dict must contain keys ``model`` and ``feature_columns`` as
    written by :func:`train.save_baseline_artifact`.
    """
    with BASELINE_MODEL_PATH.open("rb") as f:
        data = pickle.load(f)
    return data["model"], data["feature_columns"]


@st.cache_resource
def load_nn() -> tuple[PassPredictor, object, list[str]]:
    """
    Reconstruct the PyTorch MLP, fitted StandardScaler, and feature schema.

    ``weights_only=False`` is required because the checkpoint embeds the
    sklearn scaler object (trusted local artifact only).
    """
    checkpoint = torch.load(FAIR_MODEL_PATH, map_location="cpu", weights_only=False)
    feature_columns: list[str] = checkpoint["feature_columns"]
    model = PassPredictor(
        input_dim=checkpoint.get("input_dim", len(feature_columns)),
        hidden_size=checkpoint.get("hidden_size", NN_HIDDEN_SIZE),
        dropout=checkpoint.get("dropout", NN_DROPOUT),
    )
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()
    return model, checkpoint["scaler"], feature_columns


@st.cache_data
def load_metrics() -> dict:
    """Load test-set metrics JSON written by ``train.py`` (empty dict if missing)."""
    if METRICS_PATH.exists():
        return json.loads(METRICS_PATH.read_text(encoding="utf-8"))
    return {}


def student_features(
    studytime: int,
    failures: int,
    absences: int,
    goout: int,
    medu: int,
    fedu: int,
    mjob: str,
    fjob: str,
    reason: str,
    feature_columns: list[str],
) -> pd.DataFrame:
    """
    Convert sidebar inputs into a one-row matrix aligned to training columns.

    Must mirror the training pipeline: raw dict → :func:`build_feature_matrix`
    → :func:`align_to_training_columns` so XGBoost and the NN see the same
    encoding as during ``train.py``.
    """
    raw = pd.DataFrame(
        [
            {
                "studytime": studytime,
                "failures": failures,
                "absences": absences,
                "goout": goout,
                "Medu": medu,
                "Fedu": fedu,
                "Mjob": mjob,
                "Fjob": fjob,
                "reason": reason,
            }
        ]
    )
    features = build_feature_matrix(raw)
    return align_to_training_columns(features, feature_columns)


def nn_pass_probability(model: PassPredictor, scaler, features: pd.DataFrame) -> float:
    """Estimated P(pass) from sigmoid(logits) for display in the UI."""
    scaled = scaler.transform(features)
    tensor_x = torch.tensor(scaled, dtype=torch.float32)
    with torch.no_grad():
        return float(torch.sigmoid(model(tensor_x)).item())


def show_result(label: str, prediction: int, probability: float) -> None:
    """Render pass/fail label and calibrated pass probability for one model."""
    outcome = "Pass" if prediction == 1 else "Fail"
    st.subheader(label)
    st.write(f"**{outcome}** — {probability * 100:.1f}% pass probability")


def render_test_metrics(metrics: dict) -> None:
    """Display hold-out accuracy and disparate impact from ``metrics.json``."""
    baseline = metrics.get("baseline", {})
    fair = metrics.get("fair", {})

    if baseline.get("accuracy") is None:
        st.caption("Run `python train.py` to generate `metrics.json` with test-set stats.")
        return

    st.subheader("Test-set metrics (from training)")
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("XGBoost accuracy", f"{baseline['accuracy']:.1%}")
    col2.metric("Neural net accuracy", f"{fair['accuracy']:.1%}")
    col3.metric(
        "XGBoost disparate impact",
        f"{baseline['disparate_impact']:.2f}",
        help="Urban predicted pass rate / rural predicted pass rate. Closer to 1.0 is fairer.",
    )
    col4.metric(
        "Neural net disparate impact",
        f"{fair['disparate_impact']:.2f}",
        help="Urban predicted pass rate / rural predicted pass rate. Closer to 1.0 is fairer.",
    )
    st.caption(
        "Disparate impact = P(pass | Urban) / P(pass | Rural) on the hold-out set. "
        "Values near **1.0** indicate similar predicted pass rates across groups."
    )


def main() -> None:
    """Streamlit entry point."""
    st.set_page_config(page_title="FairGrade AI", page_icon="🎓", layout="wide")

    st.title("FairGrade AI")
    st.write(
        "Enter a student profile and compare two models trained on the same features: "
        "**XGBoost** (strong tabular accuracy) and a **regularized neural network** "
        "(Dropout + weight decay for smoother, fairer boundaries). "
        "Location (`address`) is **not** used as a model input."
    )

    if not BASELINE_MODEL_PATH.exists() or not FAIR_MODEL_PATH.exists():
        st.error("Models not found. From the project root, run: `python train.py`")
        st.stop()

    xgb_model, feature_columns = load_xgb()
    nn_model, scaler, _ = load_nn()
    metrics = load_metrics()

    with st.sidebar:
        st.header("Student profile")
        studytime = st.slider("Weekly study time (1–4)", 1, 4, 2)
        failures = st.slider("Past class failures (0–3)", 0, 3, 0)
        absences = st.slider("School absences", 0, 93, 6)
        goout = st.slider("Going out with friends (1–5)", 1, 5, 3)
        medu = st.selectbox("Mother's education", EDUCATION, index=2)
        fedu = st.selectbox("Father's education", EDUCATION, index=2)
        mjob = st.selectbox("Mother's job", JOBS)
        fjob = st.selectbox("Father's job", JOBS, index=3)
        reason = st.selectbox("Reason for choosing this school", REASONS)
        predict_clicked = st.button("Predict", type="primary", use_container_width=True)

    if not predict_clicked:
        st.info("Set the fields in the sidebar, then click **Predict**.")
        return

    features = student_features(
        studytime,
        failures,
        absences,
        goout,
        EDUCATION.index(medu),
        EDUCATION.index(fedu),
        mjob,
        fjob,
        reason,
        feature_columns,
    )

    xgb_prediction = int(xgb_model.predict(features)[0])
    nn_prediction = int(predict_neural_network(nn_model, scaler, features)[0])
    xgb_probability = float(xgb_model.predict_proba(features)[0, 1])
    nn_probability = nn_pass_probability(nn_model, scaler, features)

    left, right = st.columns(2)
    with left:
        show_result("XGBoost", xgb_prediction, xgb_probability)
    with right:
        show_result("Neural network", nn_prediction, nn_probability)

    if xgb_prediction != nn_prediction:
        st.warning("The two models disagree on this profile.")
    else:
        st.success("Both models agree on pass/fail for this profile.")

    render_test_metrics(metrics)

    with st.expander("Feature vector sent to the models"):
        st.dataframe(features, use_container_width=True, hide_index=True)


if __name__ == "__main__":
    main()
